HB-logger
KostiantynVorobiov/My-own-project2-Cinema pull request #6
Opened 2020-10-15 17:29 UTC by KostiantynVorobiov

2020-10-15 19:00 UTC, aleksandr-hrankin approved these changes

2020-10-15 19:00 UTC, aleksandr-hrankin commented
Good!

2020-10-15 19:27 UTC, KseniiaMakarova requested changes

2020-10-15 19:27 UTC, KseniiaMakarova commented on .gitignore
> +target/*git
```suggestion
target/*
```

2020-10-15 19:27 UTC, KseniiaMakarova commented on src/main/java/com/cinema/dao/impl/ShoppingCartDaoImpl.java
> +        logger.info("Trying to add shopping cart");
let's log the update operation as well

2020-10-15 19:27 UTC, KseniiaMakarova commented on src/main/java/com/cinema/Main.java
> +            logger.error(e);
warn level would be more suitable
and let's add the informative message here

2020-10-15 19:27 UTC, KseniiaMakarova commented on src/main/java/com/cinema/Main.java
> +            logger.error(e);
same

2020-10-16 07:08 UTC, KseniiaMakarova approved these changes

2020-10-16 07:08 UTC, KseniiaMakarova commented on src/main/java/com/cinema/dao/impl/ShoppingCartDaoImpl.java
> +            logger.info("Added new order " + shoppingCart + " successfully");
```suggestion
            logger.info("Added new shopping cart " + shoppingCart + " successfully");
```

2020-10-16 07:08 UTC, KseniiaMakarova commented on src/main/java/com/cinema/dao/impl/ShoppingCartDaoImpl.java
> +            logger.info("Updated order " + shoppingCart + " successfully");
```suggestion
            logger.info("Updated shopping cart " + shoppingCart + " successfully");
```

2020-10-21 11:40 UTC, merged