Added CinemaHallController, OrderController, ShoppingCartController, UserController with all necessary mappers and DTOs
KostiantynVorobiov/My-own-project2-Cinema pull request #9
Opened 2020-10-27 15:17 UTC by KostiantynVorobiov

2020-10-27 16:05 UTC, DmGrt reviewed
Seems everything is fine)

2020-10-27 20:16 UTC, KseniiaMakarova requested changes

2020-10-27 20:16 UTC, KseniiaMakarova commented on src/main/java/com/cinema/model/dto/UserResponseDto.java
> +    private String password;
let's not return secure data

2020-10-27 20:16 UTC, KseniiaMakarova commented on src/main/java/com/cinema/security/AuthenticationServiceImpl.java
> +        if (userFromDb != null && userFromDb.getPassword()
first - can it be null?

second - the problem is that earlier, when your user entered incorrect email, the AuthenticationException was thrown with the informative message

and now the NoSuchElementException is thrown

my advice is not to change `findByEmail()` method
but I think you won't like calling optional.get() all the time in your controllers, so let's create `getById(Long userId)` and pass userId as the `@RequestParam` to the controllers?
what do you think?

2020-10-28 10:59 UTC, KseniiaMakarova requested changes

2020-10-28 10:59 UTC, KseniiaMakarova commented on src/main/java/com/cinema/dao/impl/UserDaoImpl.java
> +            return Optional.of(session.get(User.class, id));
what happens when we call Optional.of(null)?

2020-10-28 11:41 UTC, KseniiaMakarova approved these changes

2020-10-28 11:46 UTC, merged